<template>
  <a-modal
    v-model:visible="dialogVisible"
    title="选择用户"
    centered
    width="860px"
    height="660px"
    ok-text="确定"
    cancel-text="取消"
    @cancel="onCancel"
    @ok="onOk"
  >
    <a-form
      layout="inline"
      :model="formState"
    >
      <a-form-item
        label="所属机构"
        name="orgId"
      >
        <org-tree-select
          v-model:value="formState.orgId"
          style="width:220px;"
        />
      </a-form-item>
      <a-form-item
        label="账户"
        name="account"
      >
        <a-input
          v-model:value="formState.account"
          style="width:100px;"
        />
      </a-form-item>
      <a-form-item
        label="姓名"
        name="realName"
      >
        <a-input
          v-model:value="formState.realName"
          style="width:100px;"
        />
      </a-form-item>
      <a-form-item>
        <a-space>
          <a-button
            type="primary"
            @click="onQuery"
          >
            查询
            <template #icon>
              <icon-search />
            </template>
          </a-button>
          <a-button
            @click="onReset"
          >
            重置
            <template #icon>
              <icon-clear />
            </template>
          </a-button>
        </a-space>
      </a-form-item>
    </a-form>
    <base-table
      :row-selection="rowSelection"
      :columns="columns"
      :row-key="record => record.key"
      :data-source="dataSource"
      :pagination="pagination"
      :loading="loading"
      style="max-height:460px;margin-top:16px;"
      @pageSizeChange="onPageSizeChange"
      @pageChange="onPageChange"
    />
  </a-modal>
</template>
<script src="./index.ts" lang="ts"></script>
