import {
  Button, Input, Result, Divider, Row, Col, Layout, Space, Breadcrumb,
  Dropdown, Menu, PageHeader, Pagination, Checkbox, DatePicker, Form, Radio, Select, Switch,
  TreeSelect, Avatar, Badge, Card, Descriptions, Empty, List, Popconfirm, Popover, Table, Tabs, Tooltip,
  Tree, Alert, Drawer, Modal, Spin
} from 'ant-design-vue';
export default {
  Button,
  Input,
  Result,
  Divider,
  Row,
  Col,
  Layout,
  Space,
  Breadcrumb,
  Dropdown,
  Menu,
  PageHeader,
  Pagination,
  Checkbox,
  DatePicker,
  Form,
  Radio,
  Select,
  Switch,
  TreeSelect,
  Avatar,
  Badge,
  Card,
  Descriptions,
  Empty,
  List,
  Popconfirm,
  Popover,
  Table,
  Tabs,
  Tooltip,
  Tree,
  Alert,
  Drawer,
  Modal,
  Spin
};
